//
//  PrefsKeys.swift
//  MyQiwi
//
//  Created by ailton on 31/12/16.
//  Copyright © 2016 Qiwi. All rights reserved.
//

import Foundation

public struct PrefsKeys {
    
    static let PREFS_USER_ID = "PREFS_USER_ID"
    
    static let PREFS_USER_NAME = "PREFS_USER_NAME";
    static let PREFS_USER_EMAIL = "PREFS_USER_EMAIL";
    static let PREFS_USER_CPF = "PREFS_USER_CPF";
    static let PREFS_USER_CEL = "PREFS_USER_CEL";
    static let PREFS_USER_PICTURE = "PREFS_USER_PICTURE";
    static let PREFS_USER_LAST_LOGIN_DATE = "PREFS_USER_LAST_LOGIN_DATE";
    static let PREFS_USER_LAST_LOGIN_TIME = "PREFS_USER_LAST_LOGIN_TIME";
    static let PREFS_USER_IS_QIWI_ACCOUNT_ACTIVE = "PREFS_USER_IS_QIWI_ACCOUNT_ACTIVE";
    static let PREFS_USER_USA_ATM = "PREFS_USER_USA_ATM";
    static let PREFS_USER_IS_ADESAO_DIGITAL = "PREFS_USER_IS_ADESAO_DIGITAL";
    static let PREFS_USER_IS_CONTA_PRE_PAGA = "PREFS_USER_IS_CONTA_PRE_PAGA";
    static let PREFS_USER_CAN_SHOW_RECEIPT_PRE_PAGO = "PREFS_USER_CAN_SHOW_RECEIPT_PRE_PAGO";
    static let PREFS_USER_ALREADY_CLICKED_STUDENT_FORM = "PREFS_USER_ALREADY_CLICKED_STUDENT_FORM";
    static let PREFS_NEED_INITIALIZATION = "PREFS_NEED_INITIALIZATION";
    
    static let PARKING_CARD_BALANCE = "cet/cad/consulta";
    static let PARKING_SAVE_VEHICLE = "cet/veiculo/cadastrar";
    static let PARKING_DELETE_VEHICLE = "cet/veiculo/excluir";
    static let PARKING_GET_VEHICLES = "cet/veiculo/consulta";
    static let PARKING_ACTIVE_CARD = "cet/ativa";
    static let PARKING_GET_AVAILABLE_LOCAL = "cet/endereco/consulta";
    static let PARKING_STATEMENT = "cet/extrato";
    static let PARKING_STATEMENT_DETAIL = "cet/extrato/detalhe";
    
    static let PREFS_CAN_SHOW_DOC_WARNING = "PREFS_CAN_SHOW_DOC_WARNING"
    static let PREFS_DOC_STATUS = "PREFS_DOC_STATUS"
    static let PREFS_SHOW_LATER_STATUS = "PREFS_SHOW_LATER_STATUS"
    static let PREFS_CAN_SHOW_DOC_POPUP = "PREFS_CAN_SHOW_DOC_POPUP"
    static let PREFS_SENT_DOC = "PREFS_SENT_DOC"
    static let PREFS_NEED_TO_SEND_DOC = "PREFS_NEED_TO_SEND_DOC"
    static let PREFS_LAST_LOGGED_PHONE = "PREFS_LAST_LOGGED_PHONE"
    static let PREFS_EMAIL_AND_DATE_BIRTH_NEEDED = "PREFS_EMAIL_AND_DATE_BIRTH_NEEDED"
    static let PREFS_NEED_UPDATE_LIMITS = "PREFS_NEED_UPDATE_LIMITS"
    
    static let PREFS_CLICKBUS_UPDATE_NEEDED = "PREFS_CLICKBUS_UPDATE_NEEDED"
    static let PREFS_CLICKBUS_FILE_VERSION = "PREFS_CLICKBUS_FILE_VERSION"
    static let PREFS_CLICKBUS_FILE_NAME = "PREFS_CLICKBUS_FILE_NAME"
    
    static let PREFS_TERMINAL_TYPE = "PREFS_TERMINAL_TYPE"
    
    static let PREFS_PASSWORD_VISIBILITY_IS_HIDDEN = "PREFS_PASSWORD_VISIBILITY_IS_HIDDEN"
    static let PREFS_PASSWORD_VISIBILITY_CHANGE_ALL = "PREFS_PASSWORD_VISIBILITY_CHANGE_ALL"
    static let PREFS_PASSWORD_VISIBILITY_CAN_SHOW_POPUP = "PREFS_PASSWORD_VISIBILITY_CAN_SHOW_POPUP"
    
    static let PREFS_CAN_SHOW_ADESAO_POPUP = "PREFS_CAN_SHOW_ADESAO_POPUP"
    static let PREFS_INITIALIZATION_COUNT = "PREFS_INITIALIZATION_COUNT" //QUANTAS VEZES ENTROU NO APP - RESETA EM 5
    
    static let PREFS_PRIVACY_CONFIRMATION = "PREFS_PRIVACY_CONFIRMATION"
    
    static let PREFS_TERMINAL_ID = "PREFS_TERMINAL_ID";
    static let PREFS_SEQUENTIAL = "PREFS_SEQUENTIAL";
    static let PREFS_S = "PREFS_S"
    static let PREFS_REINITIALIZE_COUNT = "PREFS_REINITIALIZE_COUNT"
    
    static let PREFS_LAST_NOTIFICATION_ID = "PREFS_LAST_NOTIFICATION_ID"
    static let PREFS_LAST_PARKING_NOTIFICATION_ID = "PREFS_LAST_PARKING_NOTIFICATION_ID"
    static let PREFS_NEED_VERIFY_VEHICLES = "PREFS_NEED_VERIFY_VEHICLES"
    static let PREFS_HAS_TOKEN = "PREFS_HAS_TOKEN"
    
}
